### ISSUE TITLE
Failed simple test cases.

### ISSUE THREAD

**Issue by dichen001** [sreeramveluthakkal/FSS17_GRP_N#1]
## Tested your code by running the output generated from this code:
- How to generate test data: `python generate_test.py`
- How to test your code: `python test_sample.csv c.py  1 .1`

## `generate_test.py`
```
import random

# sample size
N = 50

def klass(x):
    global N
    if x < 0.2:
        return 0.2 + random.random()/N
    elif x < 0.6:
        return 0.6 + random.random()/N
    else:
        return 0.9 + random.random()/N

if __name__ == '__main__':
    random.seed(random.randint(0,1000))
    arr = []
    with open("test_sample.csv","w+") as fp:
        for i in range(N):
            x = random.random()
            y = klass(x)
            fp.write("%f %f\n"%(x,y))
```

## The error I got:
```
Traceback (most recent call last):
  File "c.py", line 287, in <module>
    results = parse(sys.argv[1])
  File "c.py", line 186, in parse
    data[i].append(dom(i,row,data,headers,numgoals)) #append domination rank to row
  File "c.py", line 114, in dom
    if dominate(row, otherrow, headers, numgoals):
  File "c.py", line 108, in dominate
    return sum1/n < sum2/n
ZeroDivisionError: float division by zero
```

## The input I used:
```
0.572457 0.602197
0.080682 0.206343
0.048607 0.209993
0.590069 0.607504
0.779581 0.902581
0.000778 0.204106
0.771274 0.908582
0.561187 0.604567
0.698956 0.902636
0.765079 0.907977
0.807013 0.903142
0.183597 0.202606
0.546203 0.600850
0.499503 0.607835
0.631611 0.904498
0.930935 0.901687
0.309793 0.608447
0.397150 0.600811
0.873461 0.904128
0.145540 0.204316
0.935213 0.902712
0.600445 0.906817
0.757713 0.902477
0.738153 0.906729
0.193927 0.209333
0.415190 0.601769
0.765538 0.901926
0.767028 0.907006
0.572463 0.604856
0.918813 0.908461
0.423935 0.604074
0.279313 0.607725
0.013300 0.206551
0.730151 0.906445
0.721349 0.905851
0.664942 0.900067
0.059005 0.202959
0.142250 0.209265
0.141679 0.200590
0.069195 0.206953
0.444913 0.601819
0.622509 0.908915
0.961101 0.903911
0.286445 0.608877
0.715516 0.900326
0.423807 0.603336
0.798427 0.909626
0.918216 0.902188
0.888802 0.907896
0.901901 0.906919
0.444343 0.609122
0.091755 0.204013
0.751462 0.901002
0.743832 0.908767
0.970956 0.907533
0.573346 0.608781
0.443822 0.605546
0.253542 0.602082
0.279640 0.600490
0.774170 0.902912
0.249004 0.609366
0.166217 0.205788
0.738897 0.904268
0.376686 0.604927
0.115003 0.204201
0.750225 0.907498
0.697027 0.901958
0.847735 0.906351
0.402877 0.605499
0.092712 0.200873
0.842977 0.900137
0.796259 0.908705
0.267972 0.607158
0.585835 0.609998
0.935842 0.901898
0.434414 0.608436
0.212902 0.607935
0.982712 0.904680
0.984887 0.902514
0.625664 0.904576
0.980172 0.900069
0.149220 0.204717
0.680745 0.909598
0.733342 0.903259
0.402488 0.606612
0.556102 0.608990
0.686848 0.905798
0.240026 0.604821
0.887674 0.900956
0.089465 0.202851
0.676277 0.901866
0.950101 0.904115
0.809190 0.908632
0.805013 0.902463
0.837424 0.903192
0.904729 0.900135
0.519325 0.603375
0.081482 0.208190
0.696752 0.905176
0.018731 0.202079
```

**Comment by sreeramveluthakkal** [comment]
Hi Jack,
The ZeroDivisionError: float division by zero occurs at this point - return sum1/n < sum2/n - because there are no goals in this test case (n is the number of goals). This is from HW2 where we calculate domination rank (https://lualure.github.io/info/row.html) and the rank is calculated on the goals. Also, since supervised component depends on domination rank (ergo, the goals), we can't have test cases which have no goals.
Also, the test cases seem to have no headers.
Can you please check and let us know if this is still a valid test case? If so, we can work on the required changes.

**Comment by dichen001** [comment]
OK, I see. So let's assume the second column is your goal, i.e. the single dependent variable. What should you do with the input to make your code generate a reasonable output?
Please add the modified input in the reply, as well as instructions for running your code.

Thanks!

**Comment by sreeramveluthakkal** [comment]
Hi Jack
Please find test.csv in the repo now. It has the same test data you shared above with few format edits.
Here are the edits made:
1. Added a header column ($column,<goal) The first 'column' is numeric and second is the goal.
2. Comma separated the values

Running the test - `python c.py test.csv 0 0.1`
Explanation - run c.py with input as test.csv. run the discretization on first column, with cohen value as 0.1. The cohen value depends on the data. Higher values will result in lesser bins.

The ranks can be found in output.txt, and a terminal output sample is in pipe.txt (which shows the bins)

**Comment by dichen001** [comment]
Thanks for the modification. The supervised output seems correct to me. While the unsupervised still seems kind of abnormal to me. For the unsupervised discretized, I think the logic is: keep adding data into one bin when counts < root(n) AND bin span < epsilon. Stop and create another bin when these 2 conditions are met.

Could you please check your logic for the unsupervised one? 

Getting the correct bins are very important for HW4.

**Comment by sreeramveluthakkal** [comment]
Issue fixed. Removed an unnecessary constraint set in creating bins for unsupervised
